fix: fixes for docker demo UX (#3389)
* fix: fixes for docker demo UX

- fix: deployer polling interval ignored
- fix: silently ignore building images if multiple images specified
- feat: lazydocker TUI for docker demo

* fix: restore just demo behaviour on CI

diff --git a/scripts/build-docker-images-native b/scripts/build-docker-images-native
--- a/scripts/build-docker-images-native
+++ b/scripts/build-docker-images-native
@@ -42,7 +42,14 @@ while [[ $# -gt 0 ]]; do
       usage
       exit 0
       ;;
-    --image)
+    -i|--image)
+      # abort if specified multiple times
+      if [[ -n "${image:-}" ]]; then
+        >&2 echo "Error: --image option specified multiple times"
+        >&2 echo ""
+        usage
+        exit 1
+      fi
       image="$2"
       shift 2
       ;;
